apiVersion: v1
kind: Pod
metadata:
  name: devops-002-hello
  labels:
    app.kubernetes.io/name: devops-002-hello
    my-type: backend
    my-module: hello-module
    my-project-name: devops-002
spec:
  containers:
  - name: devops-002-hello
    image: mimaraslan/devops_002_hello:v002
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
