apiVersion: v1
kind: Service
metadata:
  name: devops-002-hello
spec:
  selector:
    app: devops-002-hello
  ports:
  - port: 9090   # Service'in dinleyeceği port
    targetPort: 8080   # Pod içindeki .jar uygulamanın portu - containerPort ile aynı olmalı
  type: ClusterIP    # Service tipi (ClusterIP, NodePort, LoadBalancer, vb.)